package go_reverso_api

const urlTranslate = "https://api.reverso.net/translate/v1/translation"
const urlVoice = "https://voice.reverso.net/RestPronunciation.svc/v1/output=json/GetVoiceStream/voiceName="
const urlSynonyms = "https://synonyms.reverso.net/api/v2/"
const endpointSynonymsSearch = "search/"
const endpointSynonymsAutoComplete = "autocomplete/"
const urlAccount = "https://account.reverso.net/api/v1/account/"
const endpointAccountLogin = "Login"
const endpointAccountRegister = "Register"
const urlContextSuggest = "https://context.reverso.net/bst-suggest-service"
const urlContextQuery = "https://context.reverso.net/bst-query-service"

const userAgentContextApp = "Dalvik/2.1.0 (Linux; U; Android 9; ONEPLUS A5000 Build/PKQ1.180716.001) ReversoContext"
const userAgentContextBrowser = "Mozilla/5.0 (Linux; Android 9; ONEPLUS A5000 Build/PKQ1.180716.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.110 Mobile Safari/537.36 ReversoContext"
const userAgentSynonymsApp = ""

const VoiceArabic = "Mehdi22k"
const VoiceEnglishMale = "Ryan22k"
const VoiceEnglishFemale = "Heather22k"
const VoiceEnglishUKMale = "Peter22k"
const VoiceEnglishUKFemale = "Rachel22k"
const VoiceFrenchMale = "Bruno22k"
const VoiceFrenchFemale = "Claire22k"
const VoiceFrenchCanadianFemale = "Louise22k"
const VoiceGerman = "Klaus22k"
const VoiceItalianMale = "Vittorio22k"
const VoiceItalianFemale = "Chiara22k"
const VoicePortuguese = "Celia22k"
const VoicePortugueseBrazilian = "Marcia22k"
const VoiceSpanishMale = "Antonio22k"
const VoiceSpanishFemale = "Maria22k"
const VoiceDutchName = "Femke22k"
const VoiceRussian = "Alyona22k"
const VoicePolish = "Ania22k"
const VoiceJapanese = "Sakura22k"
const VoiceTurkish = "Ipek22k"
const VoiceHebrew = "he-IL-Asaf"
const VoiceRomanian = "ro-RO-Andrei"
const VoiceChinese = "Lulu22k"

const LanguageDutch = "dutch"
const LanguageLanguage = "japanese"
const LanguageChinese = "chinese"
const LanguageArabic = "arabic"
const LanguageItalian = "italian"
const LanguageRomanian = "romanian"
const LanguageGerman = "german"
const LanguagePortuguese = "portuguese"
const LanguageFrench = "french"
const LanguageRussian = "russian"
const LanguagePolish = "polish"
const LanguageTurkish = "turkish"
const LanguageEnglish = "english"
const LanguageSpanish = "spanish"
const LanguageHebrew = "hebrew"

const bearerSynonyms = "c3lub255bXM6REtiZTUyRjNZRExZdVFFOHlk" // synonyms:DKbe52F3YDLYuQE8yd  // probably just an identifier
